import * as strings_ar_common from './laserfiche-base/ar-EG.json';
import * as strings_en_common from './laserfiche-base/en-US.json';
import * as strings_es_common from './laserfiche-base/es-MX.json';
import * as strings_fr_common from './laserfiche-base/fr-FR.json';
import * as strings_it_common from './laserfiche-base/it-IT.json';
import * as strings_ptBR_common from './laserfiche-base/pt-BR.json';
import * as strings_th_common from './laserfiche-base/th-TH.json';
import * as strings_zhHans_common from './laserfiche-base/zh-Hans.json';
import * as strings_zhHant_common from './laserfiche-base/zh-Hant.json';
export { strings_ar_common, strings_en_common, strings_es_common, strings_fr_common, strings_it_common, strings_ptBR_common, strings_th_common, strings_zhHans_common, strings_zhHant_common };