name: lf-resource-library-ci
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NPM_VERSION: "4.0.6"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish_to_npm_preview:
    environment: npm_preview
    if: ${{ github.run_attempt != 1 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: set up variable -- NpmPackageVersion and NpmTag for preview
        run: |
          echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
        
      - name: Echo NPM package version
        run: echo ${{ env.NpmPackageVersion }}
        
      - name: Npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version

      - name: Npm publish
        run: npm publish  --access public  --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NpmPackageVersion }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}} 
          
  publish_to_npm_release:
    environment: npm_production
    if: ${{ github.run_attempt != 1 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
        
      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
    
      - name: Npm version
        run: npm version ${{ env.NPM_VERSION }} --no-git-tag-version --allow-same-version
        
      - name: Npm publish
        run: npm publish  --access public  --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.NPM_VERSION }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}} 
